//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using HatTrick.DbEx.MsSql;
using HatTrick.DbEx.Sql;
using System;
using System.Collections.Generic;
using System.Data;
using ServerSideBlazorApp.dboDataService;
using ServerSideBlazorApp.secDataService;
#nullable enable
namespace ServerSideBlazorApp.DataService
{
    public class CRMDatabaseSqlDatabaseMetadata : ISqlDatabaseMetadata
    {
        private static readonly Dictionary<int, ISqlMetadata> _metadata = new Dictionary<int, ISqlMetadata>();

        #region interface
        public string Name { get; private set; } = "MsSqlDbExTest";
        public IDictionary<int, ISqlMetadata> Metadata => _metadata;
        #endregion

        #region constructors
        static CRMDatabaseSqlDatabaseMetadata()
        {
            #region dbo schema
            _metadata.Add(1, new SqlSchemaMetadata("dbo"));
            
            #region dbo entities
            #region dbo.Address
            _metadata.Add(2, new SqlTableMetadata("Address"));
            _metadata.Add(3, new MsSqlColumnMetadata("Id", SqlDbType.Int) { IsIdentity = true });
            _metadata.Add(4, new MsSqlColumnMetadata("AddressType", SqlDbType.Int));
            _metadata.Add(5, new MsSqlColumnMetadata("Line1", SqlDbType.VarChar, 50));
            _metadata.Add(6, new MsSqlColumnMetadata("Line2", SqlDbType.VarChar, 50));
            _metadata.Add(7, new MsSqlColumnMetadata("City", SqlDbType.VarChar, 60));
            _metadata.Add(8, new MsSqlColumnMetadata("State", SqlDbType.Char, 2));
            _metadata.Add(9, new MsSqlColumnMetadata("Zip", SqlDbType.VarChar, 10));
            _metadata.Add(10, new MsSqlColumnMetadata("DateCreated", SqlDbType.DateTime));
            _metadata.Add(11, new MsSqlColumnMetadata("DateUpdated", SqlDbType.DateTime));
            #endregion

            #region dbo.Person
            _metadata.Add(12, new SqlTableMetadata("Person"));
            _metadata.Add(13, new MsSqlColumnMetadata("Id", SqlDbType.Int) { IsIdentity = true });
            _metadata.Add(14, new MsSqlColumnMetadata("FirstName", SqlDbType.VarChar, 20));
            _metadata.Add(15, new MsSqlColumnMetadata("LastName", SqlDbType.VarChar, 20));
            _metadata.Add(16, new MsSqlColumnMetadata("BirthDate", SqlDbType.Date));
            _metadata.Add(17, new MsSqlColumnMetadata("GenderType", SqlDbType.Int));
            _metadata.Add(18, new MsSqlColumnMetadata("CreditLimit", SqlDbType.Int));
            _metadata.Add(19, new MsSqlColumnMetadata("YearOfLastCreditLimitReview", SqlDbType.Int));
            _metadata.Add(20, new MsSqlColumnMetadata("RegistrationDate", SqlDbType.DateTimeOffset, 10));
            _metadata.Add(21, new MsSqlColumnMetadata("LastLoginDate", SqlDbType.DateTimeOffset, 10));
            _metadata.Add(22, new MsSqlColumnMetadata("DateCreated", SqlDbType.DateTime));
            _metadata.Add(23, new MsSqlColumnMetadata("DateUpdated", SqlDbType.DateTime));
            #endregion

            #region dbo.Person_Address
            _metadata.Add(24, new SqlTableMetadata("Person_Address"));
            _metadata.Add(25, new MsSqlColumnMetadata("Id", SqlDbType.Int) { IsIdentity = true });
            _metadata.Add(26, new MsSqlColumnMetadata("PersonId", SqlDbType.Int));
            _metadata.Add(27, new MsSqlColumnMetadata("AddressId", SqlDbType.Int));
            _metadata.Add(28, new MsSqlColumnMetadata("DateCreated", SqlDbType.DateTime));
            #endregion

            #region dbo.Product
            _metadata.Add(29, new SqlTableMetadata("Product"));
            _metadata.Add(30, new MsSqlColumnMetadata("Id", SqlDbType.Int) { IsIdentity = true });
            _metadata.Add(31, new MsSqlColumnMetadata("ProductCategoryType", SqlDbType.Int));
            _metadata.Add(32, new MsSqlColumnMetadata("Name", SqlDbType.VarChar, 80));
            _metadata.Add(33, new MsSqlColumnMetadata("Description", SqlDbType.NVarChar, 4000));
            _metadata.Add(34, new MsSqlColumnMetadata("ListPrice", SqlDbType.Money));
            _metadata.Add(35, new MsSqlColumnMetadata("Price", SqlDbType.Money));
            _metadata.Add(36, new MsSqlColumnMetadata("Quantity", SqlDbType.Int));
            _metadata.Add(37, new MsSqlColumnMetadata("Image", SqlDbType.VarBinary, -1));
            _metadata.Add(38, new MsSqlColumnMetadata("Height", SqlDbType.Decimal, 4, 1));
            _metadata.Add(39, new MsSqlColumnMetadata("Width", SqlDbType.Decimal, 4, 1));
            _metadata.Add(40, new MsSqlColumnMetadata("Depth", SqlDbType.Decimal, 4, 1));
            _metadata.Add(41, new MsSqlColumnMetadata("Weight", SqlDbType.Decimal, 4, 1));
            _metadata.Add(42, new MsSqlColumnMetadata("ShippingWeight", SqlDbType.Decimal, 4, 1));
            _metadata.Add(43, new MsSqlColumnMetadata("ValidStartTimeOfDayForPurchase", SqlDbType.Time, 5));
            _metadata.Add(44, new MsSqlColumnMetadata("ValidEndTimeOfDayForPurchase", SqlDbType.Time, 5));
            _metadata.Add(45, new MsSqlColumnMetadata("DateCreated", SqlDbType.DateTime));
            _metadata.Add(46, new MsSqlColumnMetadata("DateUpdated", SqlDbType.DateTime));
            #endregion

            #region dbo.Purchase
            _metadata.Add(47, new SqlTableMetadata("Purchase"));
            _metadata.Add(48, new MsSqlColumnMetadata("Id", SqlDbType.Int) { IsIdentity = true });
            _metadata.Add(49, new MsSqlColumnMetadata("PersonId", SqlDbType.Int));
            _metadata.Add(50, new MsSqlColumnMetadata("OrderNumber", SqlDbType.VarChar, 20));
            _metadata.Add(51, new MsSqlColumnMetadata("TotalPurchaseQuantity", SqlDbType.Int));
            _metadata.Add(52, new MsSqlColumnMetadata("TotalPurchaseAmount", SqlDbType.Money));
            _metadata.Add(53, new MsSqlColumnMetadata("PurchaseDate", SqlDbType.DateTime));
            _metadata.Add(54, new MsSqlColumnMetadata("ShipDate", SqlDbType.DateTime));
            _metadata.Add(55, new MsSqlColumnMetadata("ExpectedDeliveryDate", SqlDbType.DateTime));
            _metadata.Add(56, new MsSqlColumnMetadata("TrackingIdentifier", SqlDbType.UniqueIdentifier));
            _metadata.Add(57, new MsSqlColumnMetadata("PaymentMethodType", SqlDbType.VarChar, 20));
            _metadata.Add(58, new MsSqlColumnMetadata("PaymentSourceType", SqlDbType.VarChar, 20));
            _metadata.Add(59, new MsSqlColumnMetadata("DateCreated", SqlDbType.DateTime));
            _metadata.Add(60, new MsSqlColumnMetadata("DateUpdated", SqlDbType.DateTime));
            #endregion

            #region dbo.PurchaseLine
            _metadata.Add(61, new SqlTableMetadata("PurchaseLine"));
            _metadata.Add(62, new MsSqlColumnMetadata("Id", SqlDbType.Int) { IsIdentity = true });
            _metadata.Add(63, new MsSqlColumnMetadata("PurchaseId", SqlDbType.Int));
            _metadata.Add(64, new MsSqlColumnMetadata("ProductId", SqlDbType.Int));
            _metadata.Add(65, new MsSqlColumnMetadata("PurchasePrice", SqlDbType.Decimal, 12, 2));
            _metadata.Add(66, new MsSqlColumnMetadata("Quantity", SqlDbType.Int));
            _metadata.Add(67, new MsSqlColumnMetadata("DateCreated", SqlDbType.DateTime));
            _metadata.Add(68, new MsSqlColumnMetadata("DateUpdated", SqlDbType.DateTime));
            #endregion

            #region dbo.PersonTotalPurchasesView
            _metadata.Add(69, new SqlTableMetadata("PersonTotalPurchasesView"));
            _metadata.Add(70, new MsSqlColumnMetadata("Id", SqlDbType.Int));
            _metadata.Add(71, new MsSqlColumnMetadata("TotalAmount", SqlDbType.Money));
            _metadata.Add(72, new MsSqlColumnMetadata("TotalCount", SqlDbType.Int));
            #endregion

            #endregion

            #region dbo stored procedures
            _metadata.Add(73, new StoredProcedureMetadata("SelectPerson_As_Dynamic_With_Input"));
            _metadata.Add(74, new MsSqlParameterMetadata("@P1", SqlDbType.Int));
            _metadata.Add(75, new StoredProcedureMetadata("SelectPerson_As_Dynamic_With_Input_And_InputOutput"));
            _metadata.Add(76, new MsSqlParameterMetadata("@P1", SqlDbType.Int));
            _metadata.Add(77, new MsSqlParameterMetadata("@CreditLimit", SqlDbType.Int));
            _metadata.Add(78, new StoredProcedureMetadata("SelectPerson_As_Dynamic_With_Input_And_Output"));
            _metadata.Add(79, new MsSqlParameterMetadata("@P1", SqlDbType.Int));
            _metadata.Add(80, new MsSqlParameterMetadata("@Count", SqlDbType.Int));
            _metadata.Add(81, new StoredProcedureMetadata("SelectPerson_As_DynamicList_With_Input"));
            _metadata.Add(82, new MsSqlParameterMetadata("@P1", SqlDbType.Int));
            _metadata.Add(83, new StoredProcedureMetadata("SelectPerson_As_DynamicList_With_Input_And_InputOutput"));
            _metadata.Add(84, new MsSqlParameterMetadata("@P1", SqlDbType.Int));
            _metadata.Add(85, new MsSqlParameterMetadata("@CreditLimit", SqlDbType.Int));
            _metadata.Add(86, new StoredProcedureMetadata("SelectPerson_As_DynamicList_With_Input_And_Output"));
            _metadata.Add(87, new MsSqlParameterMetadata("@P1", SqlDbType.Int));
            _metadata.Add(88, new MsSqlParameterMetadata("@Count", SqlDbType.Int));
            _metadata.Add(89, new StoredProcedureMetadata("SelectPersonId_As_ScalarValue_With_Input"));
            _metadata.Add(90, new MsSqlParameterMetadata("@P1", SqlDbType.Int));
            _metadata.Add(91, new StoredProcedureMetadata("SelectPersonId_As_ScalarValue_With_Input_And_Default_Value"));
            _metadata.Add(92, new MsSqlParameterMetadata("@P1", SqlDbType.Int));
            _metadata.Add(93, new StoredProcedureMetadata("SelectPersonId_As_ScalarValue_With_Input_And_InputOutput"));
            _metadata.Add(94, new MsSqlParameterMetadata("@P1", SqlDbType.Int));
            _metadata.Add(95, new MsSqlParameterMetadata("@CreditLimit", SqlDbType.Int));
            _metadata.Add(96, new StoredProcedureMetadata("SelectPersonId_As_ScalarValue_With_Input_And_Output"));
            _metadata.Add(97, new MsSqlParameterMetadata("@P1", SqlDbType.Int));
            _metadata.Add(98, new MsSqlParameterMetadata("@Count", SqlDbType.Int));
            _metadata.Add(99, new StoredProcedureMetadata("SelectPersonId_As_ScalarValueList_With_Input"));
            _metadata.Add(100, new MsSqlParameterMetadata("@P1", SqlDbType.Int));
            _metadata.Add(101, new StoredProcedureMetadata("SelectPersonId_As_ScalarValueList_With_Input_And_InputOutput"));
            _metadata.Add(102, new MsSqlParameterMetadata("@P1", SqlDbType.Int));
            _metadata.Add(103, new MsSqlParameterMetadata("@CreditLimit", SqlDbType.Int));
            _metadata.Add(104, new StoredProcedureMetadata("SelectPersonId_As_ScalarValueList_With_Input_And_Output"));
            _metadata.Add(105, new MsSqlParameterMetadata("@P1", SqlDbType.Int));
            _metadata.Add(106, new MsSqlParameterMetadata("@Count", SqlDbType.Int));
            _metadata.Add(107, new StoredProcedureMetadata("UpdatePersonCreditLimit_With_Inputs"));
            _metadata.Add(108, new MsSqlParameterMetadata("@P1", SqlDbType.Int));
            _metadata.Add(109, new MsSqlParameterMetadata("@CreditLimit", SqlDbType.Int));
            #endregion
            #endregion

            #region sec schema
            _metadata.Add(110, new SqlSchemaMetadata("sec"));
            
            #region sec entities
            #region sec.Person
            _metadata.Add(111, new SqlTableMetadata("Person"));
            _metadata.Add(112, new MsSqlColumnMetadata("Id", SqlDbType.Int));
            _metadata.Add(113, new MsSqlColumnMetadata("SSN", SqlDbType.Char, 11));
            _metadata.Add(114, new MsSqlColumnMetadata("DateCreated", SqlDbType.DateTime));
            _metadata.Add(115, new MsSqlColumnMetadata("DateUpdated", SqlDbType.DateTime));
            #endregion

            #endregion

            #region sec stored procedures
            #endregion
            #endregion

        }

        public CRMDatabaseSqlDatabaseMetadata(string name)
        {
            Name = name ?? throw new ArgumentNullException(nameof(name));
        }
        #endregion
    }
}