using System;


namespace HatTrick.DbEx.Sql.Expression
{
    public partial class NullableInt64SumFunctionExpression
    {
        #region implicit operators
        public static implicit operator SelectExpression<long?>(NullableInt64SumFunctionExpression a) => new SelectExpression<long?>(new ExpressionContainer(a));
        public static implicit operator NullableInt64ExpressionMediator(NullableInt64SumFunctionExpression a) => new NullableInt64ExpressionMediator(new ExpressionContainer(a));
        public static implicit operator OrderByExpression(NullableInt64SumFunctionExpression a) => new OrderByExpression(new ExpressionContainer(a), OrderExpressionDirection.ASC);
        #endregion

        #region arithmetic operators
        #region TValue
        #region byte
        public static NullableInt64ExpressionMediator operator +(NullableInt64SumFunctionExpression a, byte b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<byte>(b)), ArithmeticExpressionOperator.Add)));
        public static NullableInt64ExpressionMediator operator -(NullableInt64SumFunctionExpression a, byte b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<byte>(b)), ArithmeticExpressionOperator.Subtract)));
        public static NullableInt64ExpressionMediator operator *(NullableInt64SumFunctionExpression a, byte b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<byte>(b)), ArithmeticExpressionOperator.Multiply)));
        public static NullableInt64ExpressionMediator operator /(NullableInt64SumFunctionExpression a, byte b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<byte>(b)), ArithmeticExpressionOperator.Divide)));
        public static NullableInt64ExpressionMediator operator %(NullableInt64SumFunctionExpression a, byte b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<byte>(b)), ArithmeticExpressionOperator.Modulo)));

        public static NullableInt64ExpressionMediator operator +(byte a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<byte>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Add)));
        public static NullableInt64ExpressionMediator operator -(byte a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<byte>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Subtract)));
        public static NullableInt64ExpressionMediator operator *(byte a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<byte>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Multiply)));
        public static NullableInt64ExpressionMediator operator /(byte a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<byte>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Divide)));
        public static NullableInt64ExpressionMediator operator %(byte a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<byte>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Modulo)));

        public static NullableInt64ExpressionMediator operator +(NullableInt64SumFunctionExpression a, byte? b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<byte?>(b)), ArithmeticExpressionOperator.Add)));
        public static NullableInt64ExpressionMediator operator -(NullableInt64SumFunctionExpression a, byte? b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<byte?>(b)), ArithmeticExpressionOperator.Subtract)));
        public static NullableInt64ExpressionMediator operator *(NullableInt64SumFunctionExpression a, byte? b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<byte?>(b)), ArithmeticExpressionOperator.Multiply)));
        public static NullableInt64ExpressionMediator operator /(NullableInt64SumFunctionExpression a, byte? b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<byte?>(b)), ArithmeticExpressionOperator.Divide)));
        public static NullableInt64ExpressionMediator operator %(NullableInt64SumFunctionExpression a, byte? b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<byte?>(b)), ArithmeticExpressionOperator.Modulo)));

        public static NullableInt64ExpressionMediator operator +(byte? a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<byte?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Add)));
        public static NullableInt64ExpressionMediator operator -(byte? a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<byte?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Subtract)));
        public static NullableInt64ExpressionMediator operator *(byte? a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<byte?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Multiply)));
        public static NullableInt64ExpressionMediator operator /(byte? a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<byte?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Divide)));
        public static NullableInt64ExpressionMediator operator %(byte? a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<byte?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Modulo)));
        
        #endregion

        #region decimal
        public static NullableDecimalExpressionMediator operator +(NullableInt64SumFunctionExpression a, decimal b) => new NullableDecimalExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<decimal>(b)), ArithmeticExpressionOperator.Add)));
        public static NullableDecimalExpressionMediator operator -(NullableInt64SumFunctionExpression a, decimal b) => new NullableDecimalExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<decimal>(b)), ArithmeticExpressionOperator.Subtract)));
        public static NullableDecimalExpressionMediator operator *(NullableInt64SumFunctionExpression a, decimal b) => new NullableDecimalExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<decimal>(b)), ArithmeticExpressionOperator.Multiply)));
        public static NullableDecimalExpressionMediator operator /(NullableInt64SumFunctionExpression a, decimal b) => new NullableDecimalExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<decimal>(b)), ArithmeticExpressionOperator.Divide)));
        public static NullableDecimalExpressionMediator operator %(NullableInt64SumFunctionExpression a, decimal b) => new NullableDecimalExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<decimal>(b)), ArithmeticExpressionOperator.Modulo)));

        public static NullableDecimalExpressionMediator operator +(decimal a, NullableInt64SumFunctionExpression b) => new NullableDecimalExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<decimal>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Add)));
        public static NullableDecimalExpressionMediator operator -(decimal a, NullableInt64SumFunctionExpression b) => new NullableDecimalExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<decimal>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Subtract)));
        public static NullableDecimalExpressionMediator operator *(decimal a, NullableInt64SumFunctionExpression b) => new NullableDecimalExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<decimal>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Multiply)));
        public static NullableDecimalExpressionMediator operator /(decimal a, NullableInt64SumFunctionExpression b) => new NullableDecimalExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<decimal>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Divide)));
        public static NullableDecimalExpressionMediator operator %(decimal a, NullableInt64SumFunctionExpression b) => new NullableDecimalExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<decimal>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Modulo)));

        public static NullableDecimalExpressionMediator operator +(NullableInt64SumFunctionExpression a, decimal? b) => new NullableDecimalExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<decimal?>(b)), ArithmeticExpressionOperator.Add)));
        public static NullableDecimalExpressionMediator operator -(NullableInt64SumFunctionExpression a, decimal? b) => new NullableDecimalExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<decimal?>(b)), ArithmeticExpressionOperator.Subtract)));
        public static NullableDecimalExpressionMediator operator *(NullableInt64SumFunctionExpression a, decimal? b) => new NullableDecimalExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<decimal?>(b)), ArithmeticExpressionOperator.Multiply)));
        public static NullableDecimalExpressionMediator operator /(NullableInt64SumFunctionExpression a, decimal? b) => new NullableDecimalExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<decimal?>(b)), ArithmeticExpressionOperator.Divide)));
        public static NullableDecimalExpressionMediator operator %(NullableInt64SumFunctionExpression a, decimal? b) => new NullableDecimalExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<decimal?>(b)), ArithmeticExpressionOperator.Modulo)));

        public static NullableDecimalExpressionMediator operator +(decimal? a, NullableInt64SumFunctionExpression b) => new NullableDecimalExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<decimal?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Add)));
        public static NullableDecimalExpressionMediator operator -(decimal? a, NullableInt64SumFunctionExpression b) => new NullableDecimalExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<decimal?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Subtract)));
        public static NullableDecimalExpressionMediator operator *(decimal? a, NullableInt64SumFunctionExpression b) => new NullableDecimalExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<decimal?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Multiply)));
        public static NullableDecimalExpressionMediator operator /(decimal? a, NullableInt64SumFunctionExpression b) => new NullableDecimalExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<decimal?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Divide)));
        public static NullableDecimalExpressionMediator operator %(decimal? a, NullableInt64SumFunctionExpression b) => new NullableDecimalExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<decimal?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Modulo)));
        
        #endregion

        #region double
        public static NullableDoubleExpressionMediator operator +(NullableInt64SumFunctionExpression a, double b) => new NullableDoubleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<double>(b)), ArithmeticExpressionOperator.Add)));
        public static NullableDoubleExpressionMediator operator -(NullableInt64SumFunctionExpression a, double b) => new NullableDoubleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<double>(b)), ArithmeticExpressionOperator.Subtract)));
        public static NullableDoubleExpressionMediator operator *(NullableInt64SumFunctionExpression a, double b) => new NullableDoubleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<double>(b)), ArithmeticExpressionOperator.Multiply)));
        public static NullableDoubleExpressionMediator operator /(NullableInt64SumFunctionExpression a, double b) => new NullableDoubleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<double>(b)), ArithmeticExpressionOperator.Divide)));
        public static NullableDoubleExpressionMediator operator %(NullableInt64SumFunctionExpression a, double b) => new NullableDoubleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<double>(b)), ArithmeticExpressionOperator.Modulo)));

        public static NullableDoubleExpressionMediator operator +(double a, NullableInt64SumFunctionExpression b) => new NullableDoubleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<double>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Add)));
        public static NullableDoubleExpressionMediator operator -(double a, NullableInt64SumFunctionExpression b) => new NullableDoubleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<double>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Subtract)));
        public static NullableDoubleExpressionMediator operator *(double a, NullableInt64SumFunctionExpression b) => new NullableDoubleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<double>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Multiply)));
        public static NullableDoubleExpressionMediator operator /(double a, NullableInt64SumFunctionExpression b) => new NullableDoubleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<double>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Divide)));
        public static NullableDoubleExpressionMediator operator %(double a, NullableInt64SumFunctionExpression b) => new NullableDoubleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<double>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Modulo)));

        public static NullableDoubleExpressionMediator operator +(NullableInt64SumFunctionExpression a, double? b) => new NullableDoubleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<double?>(b)), ArithmeticExpressionOperator.Add)));
        public static NullableDoubleExpressionMediator operator -(NullableInt64SumFunctionExpression a, double? b) => new NullableDoubleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<double?>(b)), ArithmeticExpressionOperator.Subtract)));
        public static NullableDoubleExpressionMediator operator *(NullableInt64SumFunctionExpression a, double? b) => new NullableDoubleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<double?>(b)), ArithmeticExpressionOperator.Multiply)));
        public static NullableDoubleExpressionMediator operator /(NullableInt64SumFunctionExpression a, double? b) => new NullableDoubleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<double?>(b)), ArithmeticExpressionOperator.Divide)));
        public static NullableDoubleExpressionMediator operator %(NullableInt64SumFunctionExpression a, double? b) => new NullableDoubleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<double?>(b)), ArithmeticExpressionOperator.Modulo)));

        public static NullableDoubleExpressionMediator operator +(double? a, NullableInt64SumFunctionExpression b) => new NullableDoubleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<double?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Add)));
        public static NullableDoubleExpressionMediator operator -(double? a, NullableInt64SumFunctionExpression b) => new NullableDoubleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<double?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Subtract)));
        public static NullableDoubleExpressionMediator operator *(double? a, NullableInt64SumFunctionExpression b) => new NullableDoubleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<double?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Multiply)));
        public static NullableDoubleExpressionMediator operator /(double? a, NullableInt64SumFunctionExpression b) => new NullableDoubleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<double?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Divide)));
        public static NullableDoubleExpressionMediator operator %(double? a, NullableInt64SumFunctionExpression b) => new NullableDoubleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<double?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Modulo)));
        
        #endregion

        #region float
        public static NullableSingleExpressionMediator operator +(NullableInt64SumFunctionExpression a, float b) => new NullableSingleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<float>(b)), ArithmeticExpressionOperator.Add)));
        public static NullableSingleExpressionMediator operator -(NullableInt64SumFunctionExpression a, float b) => new NullableSingleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<float>(b)), ArithmeticExpressionOperator.Subtract)));
        public static NullableSingleExpressionMediator operator *(NullableInt64SumFunctionExpression a, float b) => new NullableSingleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<float>(b)), ArithmeticExpressionOperator.Multiply)));
        public static NullableSingleExpressionMediator operator /(NullableInt64SumFunctionExpression a, float b) => new NullableSingleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<float>(b)), ArithmeticExpressionOperator.Divide)));
        public static NullableSingleExpressionMediator operator %(NullableInt64SumFunctionExpression a, float b) => new NullableSingleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<float>(b)), ArithmeticExpressionOperator.Modulo)));

        public static NullableSingleExpressionMediator operator +(float a, NullableInt64SumFunctionExpression b) => new NullableSingleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<float>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Add)));
        public static NullableSingleExpressionMediator operator -(float a, NullableInt64SumFunctionExpression b) => new NullableSingleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<float>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Subtract)));
        public static NullableSingleExpressionMediator operator *(float a, NullableInt64SumFunctionExpression b) => new NullableSingleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<float>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Multiply)));
        public static NullableSingleExpressionMediator operator /(float a, NullableInt64SumFunctionExpression b) => new NullableSingleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<float>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Divide)));
        public static NullableSingleExpressionMediator operator %(float a, NullableInt64SumFunctionExpression b) => new NullableSingleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<float>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Modulo)));

        public static NullableSingleExpressionMediator operator +(NullableInt64SumFunctionExpression a, float? b) => new NullableSingleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<float?>(b)), ArithmeticExpressionOperator.Add)));
        public static NullableSingleExpressionMediator operator -(NullableInt64SumFunctionExpression a, float? b) => new NullableSingleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<float?>(b)), ArithmeticExpressionOperator.Subtract)));
        public static NullableSingleExpressionMediator operator *(NullableInt64SumFunctionExpression a, float? b) => new NullableSingleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<float?>(b)), ArithmeticExpressionOperator.Multiply)));
        public static NullableSingleExpressionMediator operator /(NullableInt64SumFunctionExpression a, float? b) => new NullableSingleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<float?>(b)), ArithmeticExpressionOperator.Divide)));
        public static NullableSingleExpressionMediator operator %(NullableInt64SumFunctionExpression a, float? b) => new NullableSingleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<float?>(b)), ArithmeticExpressionOperator.Modulo)));

        public static NullableSingleExpressionMediator operator +(float? a, NullableInt64SumFunctionExpression b) => new NullableSingleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<float?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Add)));
        public static NullableSingleExpressionMediator operator -(float? a, NullableInt64SumFunctionExpression b) => new NullableSingleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<float?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Subtract)));
        public static NullableSingleExpressionMediator operator *(float? a, NullableInt64SumFunctionExpression b) => new NullableSingleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<float?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Multiply)));
        public static NullableSingleExpressionMediator operator /(float? a, NullableInt64SumFunctionExpression b) => new NullableSingleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<float?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Divide)));
        public static NullableSingleExpressionMediator operator %(float? a, NullableInt64SumFunctionExpression b) => new NullableSingleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<float?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Modulo)));
        
        #endregion

        #region short
        public static NullableInt64ExpressionMediator operator +(NullableInt64SumFunctionExpression a, short b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<short>(b)), ArithmeticExpressionOperator.Add)));
        public static NullableInt64ExpressionMediator operator -(NullableInt64SumFunctionExpression a, short b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<short>(b)), ArithmeticExpressionOperator.Subtract)));
        public static NullableInt64ExpressionMediator operator *(NullableInt64SumFunctionExpression a, short b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<short>(b)), ArithmeticExpressionOperator.Multiply)));
        public static NullableInt64ExpressionMediator operator /(NullableInt64SumFunctionExpression a, short b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<short>(b)), ArithmeticExpressionOperator.Divide)));
        public static NullableInt64ExpressionMediator operator %(NullableInt64SumFunctionExpression a, short b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<short>(b)), ArithmeticExpressionOperator.Modulo)));

        public static NullableInt64ExpressionMediator operator +(short a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<short>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Add)));
        public static NullableInt64ExpressionMediator operator -(short a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<short>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Subtract)));
        public static NullableInt64ExpressionMediator operator *(short a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<short>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Multiply)));
        public static NullableInt64ExpressionMediator operator /(short a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<short>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Divide)));
        public static NullableInt64ExpressionMediator operator %(short a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<short>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Modulo)));

        public static NullableInt64ExpressionMediator operator +(NullableInt64SumFunctionExpression a, short? b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<short?>(b)), ArithmeticExpressionOperator.Add)));
        public static NullableInt64ExpressionMediator operator -(NullableInt64SumFunctionExpression a, short? b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<short?>(b)), ArithmeticExpressionOperator.Subtract)));
        public static NullableInt64ExpressionMediator operator *(NullableInt64SumFunctionExpression a, short? b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<short?>(b)), ArithmeticExpressionOperator.Multiply)));
        public static NullableInt64ExpressionMediator operator /(NullableInt64SumFunctionExpression a, short? b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<short?>(b)), ArithmeticExpressionOperator.Divide)));
        public static NullableInt64ExpressionMediator operator %(NullableInt64SumFunctionExpression a, short? b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<short?>(b)), ArithmeticExpressionOperator.Modulo)));

        public static NullableInt64ExpressionMediator operator +(short? a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<short?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Add)));
        public static NullableInt64ExpressionMediator operator -(short? a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<short?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Subtract)));
        public static NullableInt64ExpressionMediator operator *(short? a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<short?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Multiply)));
        public static NullableInt64ExpressionMediator operator /(short? a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<short?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Divide)));
        public static NullableInt64ExpressionMediator operator %(short? a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<short?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Modulo)));
        
        #endregion

        #region int
        public static NullableInt64ExpressionMediator operator +(NullableInt64SumFunctionExpression a, int b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<int>(b)), ArithmeticExpressionOperator.Add)));
        public static NullableInt64ExpressionMediator operator -(NullableInt64SumFunctionExpression a, int b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<int>(b)), ArithmeticExpressionOperator.Subtract)));
        public static NullableInt64ExpressionMediator operator *(NullableInt64SumFunctionExpression a, int b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<int>(b)), ArithmeticExpressionOperator.Multiply)));
        public static NullableInt64ExpressionMediator operator /(NullableInt64SumFunctionExpression a, int b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<int>(b)), ArithmeticExpressionOperator.Divide)));
        public static NullableInt64ExpressionMediator operator %(NullableInt64SumFunctionExpression a, int b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<int>(b)), ArithmeticExpressionOperator.Modulo)));

        public static NullableInt64ExpressionMediator operator +(int a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<int>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Add)));
        public static NullableInt64ExpressionMediator operator -(int a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<int>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Subtract)));
        public static NullableInt64ExpressionMediator operator *(int a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<int>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Multiply)));
        public static NullableInt64ExpressionMediator operator /(int a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<int>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Divide)));
        public static NullableInt64ExpressionMediator operator %(int a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<int>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Modulo)));

        public static NullableInt64ExpressionMediator operator +(NullableInt64SumFunctionExpression a, int? b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<int?>(b)), ArithmeticExpressionOperator.Add)));
        public static NullableInt64ExpressionMediator operator -(NullableInt64SumFunctionExpression a, int? b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<int?>(b)), ArithmeticExpressionOperator.Subtract)));
        public static NullableInt64ExpressionMediator operator *(NullableInt64SumFunctionExpression a, int? b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<int?>(b)), ArithmeticExpressionOperator.Multiply)));
        public static NullableInt64ExpressionMediator operator /(NullableInt64SumFunctionExpression a, int? b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<int?>(b)), ArithmeticExpressionOperator.Divide)));
        public static NullableInt64ExpressionMediator operator %(NullableInt64SumFunctionExpression a, int? b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<int?>(b)), ArithmeticExpressionOperator.Modulo)));

        public static NullableInt64ExpressionMediator operator +(int? a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<int?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Add)));
        public static NullableInt64ExpressionMediator operator -(int? a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<int?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Subtract)));
        public static NullableInt64ExpressionMediator operator *(int? a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<int?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Multiply)));
        public static NullableInt64ExpressionMediator operator /(int? a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<int?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Divide)));
        public static NullableInt64ExpressionMediator operator %(int? a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<int?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Modulo)));
        
        #endregion

        #region long
        public static NullableInt64ExpressionMediator operator +(NullableInt64SumFunctionExpression a, long b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<long>(b)), ArithmeticExpressionOperator.Add)));
        public static NullableInt64ExpressionMediator operator -(NullableInt64SumFunctionExpression a, long b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<long>(b)), ArithmeticExpressionOperator.Subtract)));
        public static NullableInt64ExpressionMediator operator *(NullableInt64SumFunctionExpression a, long b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<long>(b)), ArithmeticExpressionOperator.Multiply)));
        public static NullableInt64ExpressionMediator operator /(NullableInt64SumFunctionExpression a, long b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<long>(b)), ArithmeticExpressionOperator.Divide)));
        public static NullableInt64ExpressionMediator operator %(NullableInt64SumFunctionExpression a, long b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<long>(b)), ArithmeticExpressionOperator.Modulo)));

        public static NullableInt64ExpressionMediator operator +(long a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<long>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Add)));
        public static NullableInt64ExpressionMediator operator -(long a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<long>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Subtract)));
        public static NullableInt64ExpressionMediator operator *(long a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<long>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Multiply)));
        public static NullableInt64ExpressionMediator operator /(long a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<long>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Divide)));
        public static NullableInt64ExpressionMediator operator %(long a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<long>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Modulo)));

        public static NullableInt64ExpressionMediator operator +(NullableInt64SumFunctionExpression a, long? b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<long?>(b)), ArithmeticExpressionOperator.Add)));
        public static NullableInt64ExpressionMediator operator -(NullableInt64SumFunctionExpression a, long? b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<long?>(b)), ArithmeticExpressionOperator.Subtract)));
        public static NullableInt64ExpressionMediator operator *(NullableInt64SumFunctionExpression a, long? b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<long?>(b)), ArithmeticExpressionOperator.Multiply)));
        public static NullableInt64ExpressionMediator operator /(NullableInt64SumFunctionExpression a, long? b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<long?>(b)), ArithmeticExpressionOperator.Divide)));
        public static NullableInt64ExpressionMediator operator %(NullableInt64SumFunctionExpression a, long? b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<long?>(b)), ArithmeticExpressionOperator.Modulo)));

        public static NullableInt64ExpressionMediator operator +(long? a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<long?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Add)));
        public static NullableInt64ExpressionMediator operator -(long? a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<long?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Subtract)));
        public static NullableInt64ExpressionMediator operator *(long? a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<long?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Multiply)));
        public static NullableInt64ExpressionMediator operator /(long? a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<long?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Divide)));
        public static NullableInt64ExpressionMediator operator %(long? a, NullableInt64SumFunctionExpression b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(new LiteralExpression<long?>(a)), new ExpressionContainer(b), ArithmeticExpressionOperator.Modulo)));
        
        #endregion

        #endregion

        #region mediator
        #region byte
        public static NullableInt64ExpressionMediator operator +(NullableInt64SumFunctionExpression a, ByteExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Add)));
        public static NullableInt64ExpressionMediator operator -(NullableInt64SumFunctionExpression a, ByteExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Subtract)));
        public static NullableInt64ExpressionMediator operator *(NullableInt64SumFunctionExpression a, ByteExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Multiply)));
        public static NullableInt64ExpressionMediator operator /(NullableInt64SumFunctionExpression a, ByteExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Divide)));
        public static NullableInt64ExpressionMediator operator %(NullableInt64SumFunctionExpression a, ByteExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Modulo)));

        public static NullableInt64ExpressionMediator operator +(NullableInt64SumFunctionExpression a, NullableByteExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Add)));
        public static NullableInt64ExpressionMediator operator -(NullableInt64SumFunctionExpression a, NullableByteExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Subtract)));
        public static NullableInt64ExpressionMediator operator *(NullableInt64SumFunctionExpression a, NullableByteExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Multiply)));
        public static NullableInt64ExpressionMediator operator /(NullableInt64SumFunctionExpression a, NullableByteExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Divide)));
        public static NullableInt64ExpressionMediator operator %(NullableInt64SumFunctionExpression a, NullableByteExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Modulo)));
        #endregion

        #region decimal
        public static NullableDecimalExpressionMediator operator +(NullableInt64SumFunctionExpression a, DecimalExpressionMediator b) => new NullableDecimalExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Add)));
        public static NullableDecimalExpressionMediator operator -(NullableInt64SumFunctionExpression a, DecimalExpressionMediator b) => new NullableDecimalExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Subtract)));
        public static NullableDecimalExpressionMediator operator *(NullableInt64SumFunctionExpression a, DecimalExpressionMediator b) => new NullableDecimalExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Multiply)));
        public static NullableDecimalExpressionMediator operator /(NullableInt64SumFunctionExpression a, DecimalExpressionMediator b) => new NullableDecimalExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Divide)));
        public static NullableDecimalExpressionMediator operator %(NullableInt64SumFunctionExpression a, DecimalExpressionMediator b) => new NullableDecimalExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Modulo)));

        public static NullableDecimalExpressionMediator operator +(NullableInt64SumFunctionExpression a, NullableDecimalExpressionMediator b) => new NullableDecimalExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Add)));
        public static NullableDecimalExpressionMediator operator -(NullableInt64SumFunctionExpression a, NullableDecimalExpressionMediator b) => new NullableDecimalExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Subtract)));
        public static NullableDecimalExpressionMediator operator *(NullableInt64SumFunctionExpression a, NullableDecimalExpressionMediator b) => new NullableDecimalExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Multiply)));
        public static NullableDecimalExpressionMediator operator /(NullableInt64SumFunctionExpression a, NullableDecimalExpressionMediator b) => new NullableDecimalExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Divide)));
        public static NullableDecimalExpressionMediator operator %(NullableInt64SumFunctionExpression a, NullableDecimalExpressionMediator b) => new NullableDecimalExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Modulo)));
        #endregion

        #region double
        public static NullableDoubleExpressionMediator operator +(NullableInt64SumFunctionExpression a, DoubleExpressionMediator b) => new NullableDoubleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Add)));
        public static NullableDoubleExpressionMediator operator -(NullableInt64SumFunctionExpression a, DoubleExpressionMediator b) => new NullableDoubleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Subtract)));
        public static NullableDoubleExpressionMediator operator *(NullableInt64SumFunctionExpression a, DoubleExpressionMediator b) => new NullableDoubleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Multiply)));
        public static NullableDoubleExpressionMediator operator /(NullableInt64SumFunctionExpression a, DoubleExpressionMediator b) => new NullableDoubleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Divide)));
        public static NullableDoubleExpressionMediator operator %(NullableInt64SumFunctionExpression a, DoubleExpressionMediator b) => new NullableDoubleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Modulo)));

        public static NullableDoubleExpressionMediator operator +(NullableInt64SumFunctionExpression a, NullableDoubleExpressionMediator b) => new NullableDoubleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Add)));
        public static NullableDoubleExpressionMediator operator -(NullableInt64SumFunctionExpression a, NullableDoubleExpressionMediator b) => new NullableDoubleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Subtract)));
        public static NullableDoubleExpressionMediator operator *(NullableInt64SumFunctionExpression a, NullableDoubleExpressionMediator b) => new NullableDoubleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Multiply)));
        public static NullableDoubleExpressionMediator operator /(NullableInt64SumFunctionExpression a, NullableDoubleExpressionMediator b) => new NullableDoubleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Divide)));
        public static NullableDoubleExpressionMediator operator %(NullableInt64SumFunctionExpression a, NullableDoubleExpressionMediator b) => new NullableDoubleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Modulo)));
        #endregion

        #region float
        public static NullableSingleExpressionMediator operator +(NullableInt64SumFunctionExpression a, SingleExpressionMediator b) => new NullableSingleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Add)));
        public static NullableSingleExpressionMediator operator -(NullableInt64SumFunctionExpression a, SingleExpressionMediator b) => new NullableSingleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Subtract)));
        public static NullableSingleExpressionMediator operator *(NullableInt64SumFunctionExpression a, SingleExpressionMediator b) => new NullableSingleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Multiply)));
        public static NullableSingleExpressionMediator operator /(NullableInt64SumFunctionExpression a, SingleExpressionMediator b) => new NullableSingleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Divide)));
        public static NullableSingleExpressionMediator operator %(NullableInt64SumFunctionExpression a, SingleExpressionMediator b) => new NullableSingleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Modulo)));

        public static NullableSingleExpressionMediator operator +(NullableInt64SumFunctionExpression a, NullableSingleExpressionMediator b) => new NullableSingleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Add)));
        public static NullableSingleExpressionMediator operator -(NullableInt64SumFunctionExpression a, NullableSingleExpressionMediator b) => new NullableSingleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Subtract)));
        public static NullableSingleExpressionMediator operator *(NullableInt64SumFunctionExpression a, NullableSingleExpressionMediator b) => new NullableSingleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Multiply)));
        public static NullableSingleExpressionMediator operator /(NullableInt64SumFunctionExpression a, NullableSingleExpressionMediator b) => new NullableSingleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Divide)));
        public static NullableSingleExpressionMediator operator %(NullableInt64SumFunctionExpression a, NullableSingleExpressionMediator b) => new NullableSingleExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Modulo)));
        #endregion

        #region short
        public static NullableInt64ExpressionMediator operator +(NullableInt64SumFunctionExpression a, Int16ExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Add)));
        public static NullableInt64ExpressionMediator operator -(NullableInt64SumFunctionExpression a, Int16ExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Subtract)));
        public static NullableInt64ExpressionMediator operator *(NullableInt64SumFunctionExpression a, Int16ExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Multiply)));
        public static NullableInt64ExpressionMediator operator /(NullableInt64SumFunctionExpression a, Int16ExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Divide)));
        public static NullableInt64ExpressionMediator operator %(NullableInt64SumFunctionExpression a, Int16ExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Modulo)));

        public static NullableInt64ExpressionMediator operator +(NullableInt64SumFunctionExpression a, NullableInt16ExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Add)));
        public static NullableInt64ExpressionMediator operator -(NullableInt64SumFunctionExpression a, NullableInt16ExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Subtract)));
        public static NullableInt64ExpressionMediator operator *(NullableInt64SumFunctionExpression a, NullableInt16ExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Multiply)));
        public static NullableInt64ExpressionMediator operator /(NullableInt64SumFunctionExpression a, NullableInt16ExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Divide)));
        public static NullableInt64ExpressionMediator operator %(NullableInt64SumFunctionExpression a, NullableInt16ExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Modulo)));
        #endregion

        #region int
        public static NullableInt64ExpressionMediator operator +(NullableInt64SumFunctionExpression a, Int32ExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Add)));
        public static NullableInt64ExpressionMediator operator -(NullableInt64SumFunctionExpression a, Int32ExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Subtract)));
        public static NullableInt64ExpressionMediator operator *(NullableInt64SumFunctionExpression a, Int32ExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Multiply)));
        public static NullableInt64ExpressionMediator operator /(NullableInt64SumFunctionExpression a, Int32ExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Divide)));
        public static NullableInt64ExpressionMediator operator %(NullableInt64SumFunctionExpression a, Int32ExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Modulo)));

        public static NullableInt64ExpressionMediator operator +(NullableInt64SumFunctionExpression a, NullableInt32ExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Add)));
        public static NullableInt64ExpressionMediator operator -(NullableInt64SumFunctionExpression a, NullableInt32ExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Subtract)));
        public static NullableInt64ExpressionMediator operator *(NullableInt64SumFunctionExpression a, NullableInt32ExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Multiply)));
        public static NullableInt64ExpressionMediator operator /(NullableInt64SumFunctionExpression a, NullableInt32ExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Divide)));
        public static NullableInt64ExpressionMediator operator %(NullableInt64SumFunctionExpression a, NullableInt32ExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Modulo)));
        #endregion

        #region long
        public static NullableInt64ExpressionMediator operator +(NullableInt64SumFunctionExpression a, Int64ExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Add)));
        public static NullableInt64ExpressionMediator operator -(NullableInt64SumFunctionExpression a, Int64ExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Subtract)));
        public static NullableInt64ExpressionMediator operator *(NullableInt64SumFunctionExpression a, Int64ExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Multiply)));
        public static NullableInt64ExpressionMediator operator /(NullableInt64SumFunctionExpression a, Int64ExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Divide)));
        public static NullableInt64ExpressionMediator operator %(NullableInt64SumFunctionExpression a, Int64ExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Modulo)));

        public static NullableInt64ExpressionMediator operator +(NullableInt64SumFunctionExpression a, NullableInt64ExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Add)));
        public static NullableInt64ExpressionMediator operator -(NullableInt64SumFunctionExpression a, NullableInt64ExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Subtract)));
        public static NullableInt64ExpressionMediator operator *(NullableInt64SumFunctionExpression a, NullableInt64ExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Multiply)));
        public static NullableInt64ExpressionMediator operator /(NullableInt64SumFunctionExpression a, NullableInt64ExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Divide)));
        public static NullableInt64ExpressionMediator operator %(NullableInt64SumFunctionExpression a, NullableInt64ExpressionMediator b) => new NullableInt64ExpressionMediator(new ExpressionContainer(new ArithmeticExpression(new ExpressionContainer(a), b.Expression, ArithmeticExpressionOperator.Modulo)));
        #endregion

        #endregion
        #endregion

        #region filter operators
        #region TValue
        #region long
        public static FilterExpression<long> operator ==(NullableInt64SumFunctionExpression a, long b) => new FilterExpression<long>(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<long>(b)), FilterExpressionOperator.Equal);
        public static FilterExpression<long> operator !=(NullableInt64SumFunctionExpression a, long b) => new FilterExpression<long>(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<long>(b)), FilterExpressionOperator.NotEqual);
        public static FilterExpression<long> operator <(NullableInt64SumFunctionExpression a, long b) => new FilterExpression<long>(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<long>(b)), FilterExpressionOperator.LessThan);
        public static FilterExpression<long> operator <=(NullableInt64SumFunctionExpression a, long b) => new FilterExpression<long>(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<long>(b)), FilterExpressionOperator.LessThanOrEqual);
        public static FilterExpression<long> operator >(NullableInt64SumFunctionExpression a, long b) => new FilterExpression<long>(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<long>(b)), FilterExpressionOperator.GreaterThan);
        public static FilterExpression<long> operator >=(NullableInt64SumFunctionExpression a, long b) => new FilterExpression<long>(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<long>(b)), FilterExpressionOperator.GreaterThanOrEqual);

        public static FilterExpression<long> operator ==(long a, NullableInt64SumFunctionExpression b) => new FilterExpression<long>(new ExpressionContainer(new LiteralExpression<long>(a)), new ExpressionContainer(b), FilterExpressionOperator.Equal);
        public static FilterExpression<long> operator !=(long a, NullableInt64SumFunctionExpression b) => new FilterExpression<long>(new ExpressionContainer(new LiteralExpression<long>(a)), new ExpressionContainer(b), FilterExpressionOperator.NotEqual);
        public static FilterExpression<long> operator <(long a, NullableInt64SumFunctionExpression b) => new FilterExpression<long>(new ExpressionContainer(new LiteralExpression<long>(a)), new ExpressionContainer(b), FilterExpressionOperator.LessThan);
        public static FilterExpression<long> operator <=(long a, NullableInt64SumFunctionExpression b) => new FilterExpression<long>(new ExpressionContainer(new LiteralExpression<long>(a)), new ExpressionContainer(b), FilterExpressionOperator.LessThanOrEqual);
        public static FilterExpression<long> operator >(long a, NullableInt64SumFunctionExpression b) => new FilterExpression<long>(new ExpressionContainer(new LiteralExpression<long>(a)), new ExpressionContainer(b), FilterExpressionOperator.GreaterThan);
        public static FilterExpression<long> operator >=(long a, NullableInt64SumFunctionExpression b) => new FilterExpression<long>(new ExpressionContainer(new LiteralExpression<long>(a)), new ExpressionContainer(b), FilterExpressionOperator.GreaterThanOrEqual);

        public static FilterExpression<long> operator ==(NullableInt64SumFunctionExpression a, long? b) => new FilterExpression<long>(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<long?>(b)), FilterExpressionOperator.Equal);
        public static FilterExpression<long> operator !=(NullableInt64SumFunctionExpression a, long? b) => new FilterExpression<long>(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<long?>(b)), FilterExpressionOperator.NotEqual);
        public static FilterExpression<long> operator <(NullableInt64SumFunctionExpression a, long? b) => new FilterExpression<long>(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<long?>(b)), FilterExpressionOperator.LessThan);
        public static FilterExpression<long> operator <=(NullableInt64SumFunctionExpression a, long? b) => new FilterExpression<long>(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<long?>(b)), FilterExpressionOperator.LessThanOrEqual);
        public static FilterExpression<long> operator >(NullableInt64SumFunctionExpression a, long? b) => new FilterExpression<long>(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<long?>(b)), FilterExpressionOperator.GreaterThan);
        public static FilterExpression<long> operator >=(NullableInt64SumFunctionExpression a, long? b) => new FilterExpression<long>(new ExpressionContainer(a), new ExpressionContainer(new LiteralExpression<long?>(b)), FilterExpressionOperator.GreaterThanOrEqual);

        public static FilterExpression<long> operator ==(long? a, NullableInt64SumFunctionExpression b) => new FilterExpression<long>(new ExpressionContainer(new LiteralExpression<long?>(a)), new ExpressionContainer(b), FilterExpressionOperator.Equal);
        public static FilterExpression<long> operator !=(long? a, NullableInt64SumFunctionExpression b) => new FilterExpression<long>(new ExpressionContainer(new LiteralExpression<long?>(a)), new ExpressionContainer(b), FilterExpressionOperator.NotEqual);
        public static FilterExpression<long> operator <(long? a, NullableInt64SumFunctionExpression b) => new FilterExpression<long>(new ExpressionContainer(new LiteralExpression<long?>(a)), new ExpressionContainer(b), FilterExpressionOperator.LessThan);
        public static FilterExpression<long> operator <=(long? a, NullableInt64SumFunctionExpression b) => new FilterExpression<long>(new ExpressionContainer(new LiteralExpression<long?>(a)), new ExpressionContainer(b), FilterExpressionOperator.LessThanOrEqual);
        public static FilterExpression<long> operator >(long? a, NullableInt64SumFunctionExpression b) => new FilterExpression<long>(new ExpressionContainer(new LiteralExpression<long?>(a)), new ExpressionContainer(b), FilterExpressionOperator.GreaterThan);
        public static FilterExpression<long> operator >=(long? a, NullableInt64SumFunctionExpression b) => new FilterExpression<long>(new ExpressionContainer(new LiteralExpression<long?>(a)), new ExpressionContainer(b), FilterExpressionOperator.GreaterThanOrEqual);
        #endregion
        #endregion

        #region mediator
        public static FilterExpression<long> operator ==(NullableInt64SumFunctionExpression a, Int64ExpressionMediator b) => new FilterExpression<long>(new ExpressionContainer(a), b.Expression, FilterExpressionOperator.Equal);
        public static FilterExpression<long> operator !=(NullableInt64SumFunctionExpression a, Int64ExpressionMediator b) => new FilterExpression<long>(new ExpressionContainer(a), b.Expression, FilterExpressionOperator.NotEqual);
        public static FilterExpression<long> operator <(NullableInt64SumFunctionExpression a, Int64ExpressionMediator b) => new FilterExpression<long>(new ExpressionContainer(a), b.Expression, FilterExpressionOperator.LessThan);
        public static FilterExpression<long> operator <=(NullableInt64SumFunctionExpression a, Int64ExpressionMediator b) => new FilterExpression<long>(new ExpressionContainer(a), b.Expression, FilterExpressionOperator.LessThanOrEqual);
        public static FilterExpression<long> operator >(NullableInt64SumFunctionExpression a, Int64ExpressionMediator b) => new FilterExpression<long>(new ExpressionContainer(a), b.Expression, FilterExpressionOperator.GreaterThan);
        public static FilterExpression<long> operator >=(NullableInt64SumFunctionExpression a, Int64ExpressionMediator b) => new FilterExpression<long>(new ExpressionContainer(a), b.Expression, FilterExpressionOperator.GreaterThanOrEqual);

        public static FilterExpression<long?> operator ==(NullableInt64SumFunctionExpression a, NullableInt64ExpressionMediator b) => new FilterExpression<long?>(new ExpressionContainer(a), b.Expression, FilterExpressionOperator.Equal);
        public static FilterExpression<long?> operator !=(NullableInt64SumFunctionExpression a, NullableInt64ExpressionMediator b) => new FilterExpression<long?>(new ExpressionContainer(a), b.Expression, FilterExpressionOperator.NotEqual);
        public static FilterExpression<long?> operator <(NullableInt64SumFunctionExpression a, NullableInt64ExpressionMediator b) => new FilterExpression<long?>(new ExpressionContainer(a), b.Expression, FilterExpressionOperator.LessThan);
        public static FilterExpression<long?> operator <=(NullableInt64SumFunctionExpression a, NullableInt64ExpressionMediator b) => new FilterExpression<long?>(new ExpressionContainer(a), b.Expression, FilterExpressionOperator.LessThanOrEqual);
        public static FilterExpression<long?> operator >(NullableInt64SumFunctionExpression a, NullableInt64ExpressionMediator b) => new FilterExpression<long?>(new ExpressionContainer(a), b.Expression, FilterExpressionOperator.GreaterThan);
        public static FilterExpression<long?> operator >=(NullableInt64SumFunctionExpression a, NullableInt64ExpressionMediator b) => new FilterExpression<long?>(new ExpressionContainer(a), b.Expression, FilterExpressionOperator.GreaterThanOrEqual);
        #endregion
        #endregion
    }
}
