//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatTrick.DbEx.Sql._Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HatTrick.DbEx.Sql._Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add one or more databases, see inner exception(s) for details..
        /// </summary>
        internal static string DatabaseBuilderAggregateException {
            get {
                return ResourceManager.GetString("DatabaseBuilderAggregateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error mapping data to type &apos;{0}&apos;..
        /// </summary>
        internal static string DataMappingFailedException {
            get {
                return ResourceManager.GetString("DataMappingFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert a value from type &apos;{1}&apos; to type &apos;{0}&apos; without loss of timezone information..
        /// </summary>
        internal static string DateConversionCausesLossOfTimeZoneInformationException {
            get {
                return ResourceManager.GetString("DateConversionCausesLossOfTimeZoneInformationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service of type &apos;{0}&apos; has already been registered..
        /// </summary>
        internal static string DuplicateRegistrationException {
            get {
                return ResourceManager.GetString("DuplicateRegistrationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not initialize database type &apos;{0}&apos; for static runtime use..
        /// </summary>
        internal static string InitializeStaticRuntimeException {
            get {
                return ResourceManager.GetString("InitializeStaticRuntimeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve {0} metadata for &apos;{1}&apos;..
        /// </summary>
        internal static string MetadataResolutionException {
            get {
                return ResourceManager.GetString("MetadataResolutionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A null value was provided when a non-null value was expected..
        /// </summary>
        internal static string NullValueUnexpectedException {
            get {
                return ResourceManager.GetString("NullValueUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception publishing &apos;{0}&apos; event(s) during execution of {1} query..
        /// </summary>
        internal static string PipelineEventFailedException {
            get {
                return ResourceManager.GetString("PipelineEventFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine correct method to register the service by the provided descriptor &apos;{0}&apos;..
        /// </summary>
        internal static string RegistrationAdapterException {
            get {
                return ResourceManager.GetString("RegistrationAdapterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected type &apos;{0} &apos;to be convertible to type &apos;{1}&apos;..
        /// </summary>
        internal static string RegistrationBuilderTypeException {
            get {
                return ResourceManager.GetString("RegistrationBuilderTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not register type &apos;{0}&apos; for implementation type &apos;{1}&apos;..
        /// </summary>
        internal static string ServiceRegistrationException {
            get {
                return ResourceManager.GetString("ServiceRegistrationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve a service of type &apos;{0}&apos;..
        /// </summary>
        internal static string ServiceResolutionException {
            get {
                return ResourceManager.GetString("ServiceResolutionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dbExpression CLI tool used to generate this code (version &apos;{1}&apos;) is not compatible with the current dbExpression runtime NuGet package (version &apos;{0}&apos;).  Compatible runtime NuGet package version(s) include {2}..
        /// </summary>
        internal static string UnsupportedCodeGenTemplateVersionException {
            get {
                return ResourceManager.GetString("UnsupportedCodeGenTemplateVersionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A field with name &apos;{0}&apos; is not a field on entity &apos;{1}&apos;..
        /// </summary>
        internal static string UpdatePipelineEventNoFieldFoundException {
            get {
                return ResourceManager.GetString("UpdatePipelineEventNoFieldFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred trying to set field &apos;{0}&apos; to value &apos;{1}&apos;.
        /// </summary>
        internal static string UpdatePipelineEventSetValueFailedException {
            get {
                return ResourceManager.GetString("UpdatePipelineEventSetValueFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred converting the value &apos;{0}&apos; of type &apos;{1}&apos; to type &apos;{2}&apos;.
        /// </summary>
        internal static string ValueConversionFailedException {
            get {
                return ResourceManager.GetString("ValueConversionFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; must be greater than &apos;{1}&apos;..
        /// </summary>
        internal static string ValueMustBeGreaterThanException {
            get {
                return ResourceManager.GetString("ValueMustBeGreaterThanException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query execution requires a command of type {0}, but a command of type {1} was provided..
        /// </summary>
        internal static string WrongDbCommandTypeException {
            get {
                return ResourceManager.GetString("WrongDbCommandTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use the factory type &apos;{0}&apos; to create an instance of type &apos;{1}&apos;..
        /// </summary>
        internal static string WrongFactoryTypeException {
            get {
                return ResourceManager.GetString("WrongFactoryTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use the type &apos;{0}&apos;, type &apos;{1}&apos; was expected..
        /// </summary>
        internal static string WrongTypeException {
            get {
                return ResourceManager.GetString("WrongTypeException", resourceCulture);
            }
        }
    }
}
